; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+4 on Thu Jul 28 2022 11:07:51 GMT-0600 (Mountain Daylight Time)

; Step Back Distance
var SBD = 5  

; LED status
if exists(global.sb_leds)
  set global.sb_leds = "homing"
  ;M98 P"/sys/lib/sb_leds.g"

G91              ; relative positioning
G1 H2 Z10 F7000   ; lift Z relative to current position

; Home Y axis
G1 Y400 F3600 H1                                                             ; Move Y axis max and stop there
G1 Y{0 -var.SBD} F12000                                                       ; Move away from axis max
G1 Y400 F360 H1                                                             ; Move Y axis max and stop there
G1 Y{0 -var.SBD} F12000                                                       ; Move away from axis max

G1 H2 Z-10 F7000  ; lower Z again
G90              ; absolute positioning

; LED status
if exists(global.sb_leds)
  set global.sb_leds = "ready"
  ;M98 P"/sys/lib/sb_leds.g"