; homex.g
; called to home the X axis
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+4 on Thu Jul 28 2022 11:07:51 GMT-0600 (Mountain Daylight Time)

; XY Currrent Reduction
var CR = 32                                                                    ; The % of the XY stepper max current you want to be set during homing

; Sensorless homing sensitivity
var Sen = 2                                                                   ; Stall detection sensitivity

; Step Back Distance
var SBD = 5                                                                    ; The distance in mm that the head moves back before homing

; LED status
if exists(global.sb_leds)
  set global.sb_leds = "homing"
  ;M98 P"/sys/lib/sb_leds.g"

M913 X{var.CR} Y{var.CR} ; lower motor current for sensorless homing
M915 X Y S{var.Sen} F0 R0 H200 ; set sensorless sensitivity

G91              ; relative positioning
G1 H2 Z10 F7000   ; lift Z relative to current position

; Unflag stalls
G1 X1.0 Y-1.0 F300 H2

; Home X axis
G1 X600 F3000 H1                                                             ; Move X axis max and stop there
G1 X{0 -var.SBD} F2000                                                       ; Move away from axis max
G1 X600 F3000 H1                                                             ; Move X axis max and stop there
G1 X{0 -var.SBD} F2000                                                       ; Move away from axis max

G1 H2 Z-10 F7000  ; lower Z again
G90              ; absolute positioning

M400 ; Wait for moves to finish
M913 X100 Y100 ; Set motor power to 100%

; LED status
if exists(global.sb_leds)
  set global.sb_leds = "ready"
  ;M98 P"/sys/lib/sb_leds.g"