; homex.g
; called to home the X axis
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+4 on Thu Jul 28 2022 11:07:51 GMT-0600 (Mountain Daylight Time)

; Step Back Distance
var SBD = 5                                                                    ; The distance in mm that the head moves back before homing

; LED status
if exists(global.sb_leds)
  set global.sb_leds = "homing"
  ;M98 P"/sys/lib/sb_leds.g"

G91              ; relative positioning
G1 H2 Z10 F7000   ; lift Z relative to current position

; Home X axis
G1 X400 F3600 H1                                                             ; Move X axis max and stop there
G1 X{0 -var.SBD} F12000                                                       ; Move away from axis max
G1 X400 F360 H1                                                             ; Move X axis max and stop there
G1 X{0 -var.SBD} F12000                                                       ; Move away from axis max

G1 H2 Z-10 F7000  ; lower Z again
G90              ; absolute positioning

M400 ; Wait for moves to finish

; LED status
if exists(global.sb_leds)
  set global.sb_leds = "ready"
  ;M98 P"/sys/lib/sb_leds.g"