; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.3.16 on Thu Nov 23 2023 20:11:54 GMT+0200 (Eastern European Standard Time)
; insert codes for retracting the Z probe here

if global.TAPPING = false
  M98 P"/sys/lib/he_temp.g"                                                    ; Restore hotend temp from before probing started