; tfree0.g
; called when tool 0 is freed
;
; generated by RepRapFirmware Configuration Tool v3.3.16 on Thu Nov 23 2023 20:11:54 GMT+0200 (Eastern European Standard Time)
;G91           ; move to relative mode
;G1 E2 F800    ; extrude slightly 
;G1 E-18 F800  ; retract filament from meltzone
;G4 S2         ; dwell 2 seconds
;G1 E-10 F800  ; retract filament into thermal break