; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.5.10 on Sat Feb 22 2025 12:27:40 GMT+0200 (Eastern European Standard Time)

M116 P0 ; wait for tool temperatures to be reached
