; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.16 on Thu Nov 23 2023 20:11:55 GMT+0200 (Eastern European Standard Time)
; Wait for set temperatures to be reached
M116 P0

